/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extHash;

/**
 *
 * @author VISHNUV
 */
public class mainFrame extends javax.swing.JFrame implements allFrames{

    public static int bucketSize,gd=1,ld=1;
    public static addKeyFrame akf;
    public static int hashFunc;
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainHeading = new javax.swing.JLabel();
        bucketLabel = new javax.swing.JLabel();
        bucketSizeText = new javax.swing.JTextField();
        bucketButton = new javax.swing.JButton();
        hashFuncLabel = new javax.swing.JLabel();
        hashFuncText = new javax.swing.JTextField();
        bserr = new javax.swing.JLabel();
        hferr = new javax.swing.JLabel();
        gdldlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainHeading.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        mainHeading.setText("Extendible Hashing");

        bucketLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bucketLabel.setText("Enter the Bucket Size");

        bucketSizeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucketSizeTextActionPerformed(evt);
            }
        });

        bucketButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bucketButton.setText("Submit");
        bucketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucketButtonActionPerformed(evt);
            }
        });

        hashFuncLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hashFuncLabel.setText("Hash Function (mod)");

        bserr.setForeground(new java.awt.Color(255, 51, 0));

        hferr.setForeground(new java.awt.Color(255, 51, 0));

        gdldlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gdldlbl.setText("Global Depth: 1                         Local Depth: 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(bucketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hashFuncLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bucketLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bucketSizeText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(hashFuncText))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bserr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hferr, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gdldlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gdldlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bucketSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bucketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bserr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hferr, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(hashFuncLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hashFuncText, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bucketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bucketSizeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucketSizeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bucketSizeTextActionPerformed

    private void bucketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucketButtonActionPerformed
        // TODO add your handling code here:
        bserr.setText(null);
        hferr.setText(null);
        boolean flag=true;
        try{
            bucketSize = Integer.parseInt(bucketSizeText.getText());
            if(bucketSize==0){
                bserr.setText("Size can't be zero!");
                flag=false;
            } else if(bucketSize<0){
                bserr.setText("Size can't be -ve!");
                flag=false;
            }
        }catch(NumberFormatException e){
            bserr.setText("Enter an integer value!");
            flag=false;
        }
        try{
            hashFunc = Integer.parseInt(hashFuncText.getText());
            if(hashFunc<=0){
                hferr.setText("Enter a +ve value!");
                flag=false;
            }
        }catch(NumberFormatException e){
            hferr.setText("Enter an integer value!");
            flag=false;
        }
        if(flag){
            this.setVisible(false);
            akf = new addKeyFrame();
            akf.setVisible(true);
        }
        
        
    }//GEN-LAST:event_bucketButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bserr;
    private javax.swing.JButton bucketButton;
    private javax.swing.JLabel bucketLabel;
    private javax.swing.JTextField bucketSizeText;
    private javax.swing.JLabel gdldlbl;
    private javax.swing.JLabel hashFuncLabel;
    private javax.swing.JTextField hashFuncText;
    private javax.swing.JLabel hferr;
    private javax.swing.JLabel mainHeading;
    // End of variables declaration//GEN-END:variables
}
